pool:
  vmImage: 'windows-2022'

trigger:
  branches:
    include:
      - develop
      - main

variables:
  CSharpServerUrlIndex: 1
  fileServerUrl: 'https://int-bmm-files.brunstad.org/'
  serverUrlIndex: 1
  ##azureSubscription: 'ReplaceMe'

stages:
  - stage: BuildAndPackage
    displayName: 'Build and package'
    jobs:
      - template: 'template.build.yml'

  - stage: BuildDotnet
    dependsOn: BuildAndPackage
    displayName: 'BuildDotnet'
    jobs:
      - job: 'BuildDotnetJob'
        steps:
          - task: DownloadPipelineArtifact@2

          - script: dotnet build --configuration Release
            displayName: 'dotnet build Release'
          - script: dotnet publish -o output/
            displayName: 'dotnet publish'

          - task: CopyFiles@2
            displayName: 'Copy client files'
            inputs:
              sourceFolder: '$(Pipeline.Workspace)/dist/client/'
              targetFolder: '$(System.DefaultWorkingDirectory)/output/wwwroot'
              overWrite: true

          - task: CopyFiles@2
            displayName: 'Copy admin files'
            inputs:
              sourceFolder: '$(Pipeline.Workspace)/dist/admin/'
              targetFolder: '$(System.DefaultWorkingDirectory)/output/wwwroot/admin'

          - task: ArchiveFiles@1
            displayName: 'Archive WebApp'
            inputs:
              rootFolder: '$(System.DefaultWorkingDirectory)/output/'
              includeRootFolder: false
              archiveFile: $(System.DefaultWorkingDirectory)/output/WebApp-$(Build.BuildId).zip
          
          - publish: $(System.DefaultWorkingDirectory)
            artifact: WorkingDirectory
          - publish: $(System.DefaultWorkingDirectory)/output/WebApp-$(Build.BuildId).zip
            artifact: WebApp
  
  - stage: DeployINT
    dependsOn: BuildDotnet
    displayName: 'DeployINT'
    jobs:
    - job: 'DeployJob'
      steps:
        - task: DownloadPipelineArtifact@2

        - task: AzureRmWebAppDeployment@4
          displayName: 'Deploy Client App Service'
          inputs:
            azureSubscription: '$(azureSubscription)'
            appType: 'webApp'
            WebAppName: 'INT-BMM'
            Package: '$(Pipeline.Workspace)/WebApp/WebApp-*.zip'
            JSONFiles: '**/scripts/*.config.json'
