pool:
  vmImage: 'windows-2022'
  
variables:
  CSharpServerUrlIndex: 1
  fileServerUrl: 'https://int-bmm-files.brunstad.org/'
  serverUrlIndex: 1
  ##azureSubscription: 'ReplaceMe'

stages:
  - stage: BuildAndPackage
    displayName: 'Build and package'
    jobs:
      - template: 'template.build.yml'

  - stage: BuildDotnet
    dependsOn: BuildAndPackage
    displayName: 'BuildDotnet'
    jobs:
      - job: 'BuildDotnetJob'
        steps:
          - task: DownloadPipelineArtifact@2

          - task: CopyFiles@2
            displayName: 'Copy client files'
            inputs:
              sourceFolder: 'client/app'
              targetFolder: 'BMM.Website/wwwroot'

          - task: CopyFiles@2
            displayName: 'Copy admin files'
            inputs:
              sourceFolder: 'admin/app'
              targetFolder: 'BMM.Website/wwwroot/admin'

          - script: dotnet build --configuration Release
            displayName: 'dotnet build Release'
          - script: dotnet publish -o output/
            displayName: 'dotnet publish'

          - task: ArchiveFiles@1
            displayName: 'Archive WebApp'
            inputs:
              rootFolder: '$(System.DefaultWorkingDirectory)/output/'
              includeRootFolder: false
              archiveFile: $(System.DefaultWorkingDirectory)/output/WebApp-$(Build.BuildId).zip
          
          - publish: $(System.DefaultWorkingDirectory)
            artifact: WorkingDirectory
          - publish: $(System.DefaultWorkingDirectory)/output/WebApp-$(Build.BuildId).zip
            artifact: WebApp
  
  - stage: DeployINT
    dependsOn: BuildDotnet
    displayName: 'DeployINT'
    jobs:
    - job: 'DeployJob'
      steps:
        - task: DownloadPipelineArtifact@2

        - task: AzureRmWebAppDeployment@4
          displayName: 'Deploy Client App Service'
          inputs:
            azureSubscription: '$(azureSubscription)'
            appType: 'webApp'
            WebAppName: 'INT-BMM'
            Package: '$(Pipeline.Workspace)/WebApp/WebApp-*.zip'
            JSONFiles: '/**/scripts/config.json'
