pool:
  vmImage: 'macOS-latest'
  
variables:
  CSharpServerUrlIndex: 1
  fileServerUrl: 'https://int-bmm-files.brunstad.org/'
  serverUrlIndex: 1
  ##azureSubscription: 'ReplaceMe'

stages:
  - stage: BuildAndPackage
    displayName: 'Build and package'
    jobs:
      - template: 'template.build.yml'
  
  - stage: DeployINT
    dependsOn: BuildAndPackage
    displayName: 'DeployINT'
    jobs:
    - job: 'DeployJob'
      steps:
        - task: DownloadPipelineArtifact@2

        - task: AzureRmWebAppDeployment@3
          displayName: 'Deploy Client App Service'
          inputs:
            azureSubscription: '$(azureSubscription)'
            appType: 'Web App'
            WebAppName: 'INT-BMM'
            Package: '$(Pipeline.Workspace)/BMM Website/drop/client-*.zip'
            TakeAppOfflineFlag: true
            UseWebDeploy: true
            RemoveAdditionalFilesFlag: true
            ExcludeFilesFromAppDataFlag: true
            RenameFilesFlag: true
            JSONFiles: '/scripts/*.config.json'
            
        - task: AzureRmWebAppDeployment@3
          displayName: 'Deploy Admin App Service'
          inputs:
            azureSubscription: '$(azureSubscription)'
            appType: 'Web App'
            WebAppName: 'INT-BMM'
            VirtualApplication: /admin
            Package: '$(Pipeline.Workspace)/BMM Website/drop/admin-*.zip'
            TakeAppOfflineFlag: true
            UseWebDeploy: true
            RemoveAdditionalFilesFlag: true
            ExcludeFilesFromAppDataFlag: true
            RenameFilesFlag: true
            JSONFiles: '/scripts/*.config.json'