files:
  - source: /client_translations.json
    translation: /client/app/translations/%two_letters_code%.json
  - source: /admin_translations.json
    translation: /admin/app/translations/%two_letters_code%.json
