files:
  - source: /client-translations.json
    translation: /client/app/translations/%two_letters_code%.json
  - source: /admin-translations.json
    translation: /admin/app/translations/%two_letters_code%.json
  - source: /admin-titles.json
    translation: /admin/app/translation/titles/%two_letters_code%.json
