on:
  push:
    branches:
      - 'develop'
      - 'feature/github-actions'
  workflow_dispatch:
env:
  CSharpServerUrlIndex: 1
  fileServerUrl: https://int-bmm-files.brunstad.org/
  serverUrlIndex: 1
jobs:
  build_javascript:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 10.x for compatibility with node-sass
        uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - name: cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: common - npm install & updateCommonFiles
        run: | 
          npm install
          npm run updateCommonFiles
        working-directory: ./common

      - name: admin - build
        run: |
          npm install
          npm run bowerUpdate
          npm run build
        working-directory: ./admin

      - name: client - build
        run: |
          npm install
          npm run bowerUpdate
          npm run build
        working-directory: ./client
      
      - name: Archive output
        run: |
          zip '${{ github.workspace }}/client.zip' -r client/dist
          zip '${{ github.workspace }}/admin.zip' -r admin/dist

      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/**.zip
          name: dist
        if: (${{ job.status }} != 'cancelled')
  build_dotnet:
    runs-on: windows-latest
    needs:
      - build_javascript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - name: dotnet build Release
        run: dotnet build --configuration Release
      - name: dotnet publish
        run: dotnet publish -o output/
      - name: unzip client files
        run: unzip '${{ env.Pipeline.Workspace }}/dist/client.zip' -d '${{ github.workspace }}/output/wwwroot'
      - name: unzip admin files
        run: unzip '${{ env.Pipeline.Workspace }}/dist/admin.zip' -d '${{ github.workspace }}/output/wwwroot/admin'
        
      #- name: Copy client files
      #  run: Copy '${{ env.Pipeline.Workspace }}/dist/client//' '${{ github.workspace }}/output/wwwroot'
      #- name: Copy admin files
      #  run: Copy '${{ env.Pipeline.Workspace }}/dist/admin//' '${{ github.workspace }}/output/wwwroot/admin'
      - name: Archive output
        run: |
          zip '${{ github.workspace }}/WebApp.zip' -r output 
      #- uses: actions/upload-artifact@v2
      #  with:
      #    path: ${{ github.workspace }}
      #    name: WorkingDirectory
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/output/
          name: WebApp
#  deploy_INT:
#    runs-on: windows-latest
#    needs:
#      - build_dotnet
#    steps:
#      - uses: actions/download-artifact@v2
#      uses: microsoft/variable-substitution@v1
#        with:
#          files: '${{ env.Pipeline.Workspace }}/WebApp/appsettings.json'
#        env:
#          CSharpServerUrlIndex: 1
#      - name: Deploy Client App Service
#        uses: Azure/webapps-deploy@v2
#        with:
#          app-name: INT-BMM
#          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#          package: ${{ env.Pipeline.Workspace }}/WebApp
                    